# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syscall.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='syscall.proto',
  package='syscall_types',
  syntax='proto2',
  serialized_pb=_b('\n\rsyscall.proto\x12\rsyscall_types\x1a\x0c\x63ommon.proto\"\xda\x01\n\x0bsyscall_pol\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\x12+\n\x05ident\x18\x03 \x02(\x0e\x32\x1c.syscall_types.syscall_ident\x12&\n\x06\x61\x63tion\x18\x04 \x02(\x0e\x32\x16.common.tracing_action\x12\x1a\n\x12restrict_addresses\x18\x05 \x03(\x04\x12-\n\x07nr_read\x18\x06 \x01(\x0b\x32\x1a.syscall_types.nr_read_polH\x00\x42\x11\n\x0fsyscall_pol_cnt\"\xa4\x02\n\tsyscall_t\x12\n\n\x02id\x18\x01 \x02(\r\x12+\n\x05ident\x18\x02 \x02(\x0e\x32\x1c.syscall_types.syscall_ident\x12\x30\n\x0copen_syscall\x18\x03 \x01(\x0b\x32\x18.syscall_types.nr_open_tH\x00\x12\x30\n\x0cread_syscall\x18\x04 \x01(\x0b\x32\x18.syscall_types.nr_read_tH\x00\x12\x31\n\x0cwrite_sycall\x18\x05 \x01(\x0b\x32\x19.syscall_types.nr_write_tH\x00\x12\x36\n\x0egeneric_sycall\x18\x06 \x01(\x0b\x32\x1c.syscall_types.sys_generic_tH\x00\x42\x0f\n\rsyscall_t_cnt\"\x1b\n\x0bnr_read_pol\x12\x0c\n\x04name\x18\x01 \x02(\t\"T\n\tnr_open_t\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\r\n\x05\x66lags\x18\x02 \x02(\x11\x12\x0c\n\x04mode\x18\x03 \x02(\r\x12\x17\n\x0f\x66ile_descriptor\x18\x04 \x02(\x05\"y\n\tnr_read_t\x12\x17\n\x0f\x66ile_descriptor\x18\x01 \x02(\r\x12\x16\n\x0e\x62uffer_address\x18\x02 \x02(\x04\x12\r\n\x05\x63ount\x18\x03 \x02(\r\x12\x13\n\x0b\x62uffer_data\x18\x04 \x02(\x0c\x12\x17\n\x0f\x63ount_effective\x18\x05 \x02(\r\"z\n\nnr_write_t\x12\x17\n\x0f\x66ile_descriptor\x18\x01 \x02(\r\x12\x16\n\x0e\x62uffer_address\x18\x02 \x02(\x04\x12\r\n\x05\x63ount\x18\x03 \x02(\r\x12\x13\n\x0b\x62uffer_data\x18\x04 \x02(\x0c\x12\x17\n\x0f\x63ount_effective\x18\x05 \x02(\r\".\n\rsys_generic_t\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\r*D\n\rsyscall_ident\x12\x0b\n\x07NR_READ\x10\x00\x12\x0c\n\x08NR_WRITE\x10\x01\x12\x0b\n\x07NR_OPEN\x10\x02\x12\x0b\n\x07GENERIC\x10\x03')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SYSCALL_IDENT = _descriptor.EnumDescriptor(
  name='syscall_ident',
  full_name='syscall_types.syscall_ident',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NR_READ', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NR_WRITE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NR_OPEN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERIC', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=972,
  serialized_end=1040,
)
_sym_db.RegisterEnumDescriptor(_SYSCALL_IDENT)

syscall_ident = enum_type_wrapper.EnumTypeWrapper(_SYSCALL_IDENT)
NR_READ = 0
NR_WRITE = 1
NR_OPEN = 2
GENERIC = 3



_SYSCALL_POL = _descriptor.Descriptor(
  name='syscall_pol',
  full_name='syscall_types.syscall_pol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='syscall_types.syscall_pol.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='syscall_types.syscall_pol.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ident', full_name='syscall_types.syscall_pol.ident', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='syscall_types.syscall_pol.action', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restrict_addresses', full_name='syscall_types.syscall_pol.restrict_addresses', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nr_read', full_name='syscall_types.syscall_pol.nr_read', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='syscall_pol_cnt', full_name='syscall_types.syscall_pol.syscall_pol_cnt',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=265,
)


_SYSCALL_T = _descriptor.Descriptor(
  name='syscall_t',
  full_name='syscall_types.syscall_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='syscall_types.syscall_t.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ident', full_name='syscall_types.syscall_t.ident', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_syscall', full_name='syscall_types.syscall_t.open_syscall', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_syscall', full_name='syscall_types.syscall_t.read_syscall', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_sycall', full_name='syscall_types.syscall_t.write_sycall', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generic_sycall', full_name='syscall_types.syscall_t.generic_sycall', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='syscall_t_cnt', full_name='syscall_types.syscall_t.syscall_t_cnt',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=268,
  serialized_end=560,
)


_NR_READ_POL = _descriptor.Descriptor(
  name='nr_read_pol',
  full_name='syscall_types.nr_read_pol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='syscall_types.nr_read_pol.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=589,
)


_NR_OPEN_T = _descriptor.Descriptor(
  name='nr_open_t',
  full_name='syscall_types.nr_open_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='syscall_types.nr_open_t.file_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='syscall_types.nr_open_t.flags', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='syscall_types.nr_open_t.mode', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_descriptor', full_name='syscall_types.nr_open_t.file_descriptor', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=675,
)


_NR_READ_T = _descriptor.Descriptor(
  name='nr_read_t',
  full_name='syscall_types.nr_read_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_descriptor', full_name='syscall_types.nr_read_t.file_descriptor', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer_address', full_name='syscall_types.nr_read_t.buffer_address', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='syscall_types.nr_read_t.count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer_data', full_name='syscall_types.nr_read_t.buffer_data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count_effective', full_name='syscall_types.nr_read_t.count_effective', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=798,
)


_NR_WRITE_T = _descriptor.Descriptor(
  name='nr_write_t',
  full_name='syscall_types.nr_write_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_descriptor', full_name='syscall_types.nr_write_t.file_descriptor', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer_address', full_name='syscall_types.nr_write_t.buffer_address', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='syscall_types.nr_write_t.count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer_data', full_name='syscall_types.nr_write_t.buffer_data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count_effective', full_name='syscall_types.nr_write_t.count_effective', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=800,
  serialized_end=922,
)


_SYS_GENERIC_T = _descriptor.Descriptor(
  name='sys_generic_t',
  full_name='syscall_types.sys_generic_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='syscall_types.sys_generic_t.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='syscall_types.sys_generic_t.address', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=924,
  serialized_end=970,
)

_SYSCALL_POL.fields_by_name['ident'].enum_type = _SYSCALL_IDENT
_SYSCALL_POL.fields_by_name['action'].enum_type = common__pb2._TRACING_ACTION
_SYSCALL_POL.fields_by_name['nr_read'].message_type = _NR_READ_POL
_SYSCALL_POL.oneofs_by_name['syscall_pol_cnt'].fields.append(
  _SYSCALL_POL.fields_by_name['nr_read'])
_SYSCALL_POL.fields_by_name['nr_read'].containing_oneof = _SYSCALL_POL.oneofs_by_name['syscall_pol_cnt']
_SYSCALL_T.fields_by_name['ident'].enum_type = _SYSCALL_IDENT
_SYSCALL_T.fields_by_name['open_syscall'].message_type = _NR_OPEN_T
_SYSCALL_T.fields_by_name['read_syscall'].message_type = _NR_READ_T
_SYSCALL_T.fields_by_name['write_sycall'].message_type = _NR_WRITE_T
_SYSCALL_T.fields_by_name['generic_sycall'].message_type = _SYS_GENERIC_T
_SYSCALL_T.oneofs_by_name['syscall_t_cnt'].fields.append(
  _SYSCALL_T.fields_by_name['open_syscall'])
_SYSCALL_T.fields_by_name['open_syscall'].containing_oneof = _SYSCALL_T.oneofs_by_name['syscall_t_cnt']
_SYSCALL_T.oneofs_by_name['syscall_t_cnt'].fields.append(
  _SYSCALL_T.fields_by_name['read_syscall'])
_SYSCALL_T.fields_by_name['read_syscall'].containing_oneof = _SYSCALL_T.oneofs_by_name['syscall_t_cnt']
_SYSCALL_T.oneofs_by_name['syscall_t_cnt'].fields.append(
  _SYSCALL_T.fields_by_name['write_sycall'])
_SYSCALL_T.fields_by_name['write_sycall'].containing_oneof = _SYSCALL_T.oneofs_by_name['syscall_t_cnt']
_SYSCALL_T.oneofs_by_name['syscall_t_cnt'].fields.append(
  _SYSCALL_T.fields_by_name['generic_sycall'])
_SYSCALL_T.fields_by_name['generic_sycall'].containing_oneof = _SYSCALL_T.oneofs_by_name['syscall_t_cnt']
DESCRIPTOR.message_types_by_name['syscall_pol'] = _SYSCALL_POL
DESCRIPTOR.message_types_by_name['syscall_t'] = _SYSCALL_T
DESCRIPTOR.message_types_by_name['nr_read_pol'] = _NR_READ_POL
DESCRIPTOR.message_types_by_name['nr_open_t'] = _NR_OPEN_T
DESCRIPTOR.message_types_by_name['nr_read_t'] = _NR_READ_T
DESCRIPTOR.message_types_by_name['nr_write_t'] = _NR_WRITE_T
DESCRIPTOR.message_types_by_name['sys_generic_t'] = _SYS_GENERIC_T
DESCRIPTOR.enum_types_by_name['syscall_ident'] = _SYSCALL_IDENT

syscall_pol = _reflection.GeneratedProtocolMessageType('syscall_pol', (_message.Message,), dict(
  DESCRIPTOR = _SYSCALL_POL,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.syscall_pol)
  ))
_sym_db.RegisterMessage(syscall_pol)

syscall_t = _reflection.GeneratedProtocolMessageType('syscall_t', (_message.Message,), dict(
  DESCRIPTOR = _SYSCALL_T,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.syscall_t)
  ))
_sym_db.RegisterMessage(syscall_t)

nr_read_pol = _reflection.GeneratedProtocolMessageType('nr_read_pol', (_message.Message,), dict(
  DESCRIPTOR = _NR_READ_POL,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.nr_read_pol)
  ))
_sym_db.RegisterMessage(nr_read_pol)

nr_open_t = _reflection.GeneratedProtocolMessageType('nr_open_t', (_message.Message,), dict(
  DESCRIPTOR = _NR_OPEN_T,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.nr_open_t)
  ))
_sym_db.RegisterMessage(nr_open_t)

nr_read_t = _reflection.GeneratedProtocolMessageType('nr_read_t', (_message.Message,), dict(
  DESCRIPTOR = _NR_READ_T,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.nr_read_t)
  ))
_sym_db.RegisterMessage(nr_read_t)

nr_write_t = _reflection.GeneratedProtocolMessageType('nr_write_t', (_message.Message,), dict(
  DESCRIPTOR = _NR_WRITE_T,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.nr_write_t)
  ))
_sym_db.RegisterMessage(nr_write_t)

sys_generic_t = _reflection.GeneratedProtocolMessageType('sys_generic_t', (_message.Message,), dict(
  DESCRIPTOR = _SYS_GENERIC_T,
  __module__ = 'syscall_pb2'
  # @@protoc_insertion_point(class_scope:syscall_types.sys_generic_t)
  ))
_sym_db.RegisterMessage(sys_generic_t)


# @@protoc_insertion_point(module_scope)
