
BINSEC = 0
PINSEC = 1

EMPTY = "EMPTY"
END = "END"
EXIT = "EXIT"
START_ANALYSIS = "START_ANALYSIS"
ANALYSIS_RESULTS = "ANALYSIS_RESULTS"
DECODE_INSTR_REPLY = "DECODE_INSTR_REPLY"

TRACE_HEADER = "TRACE_HEADER"
TRACE_CHUNK = "TRACE_CHUNK"
