all:
	pyuic5 main.ui -o main_ui.py
	pyuic5 master.ui -o master_ui.py
	pyuic5 trace.ui -o trace_ui.py
	pyuic5 analysis.ui -o analysis_ui.py
	pyuic5 generic_analysis.ui -o generic_analysis_ui.py
	pyuic5 generic_analysis_result.ui -o generic_analysis_result_ui.py
	pyuic5 standard_params.ui -o standard_params_ui.py
	pyuic5 static_iteration_config.ui -o static_iteration_config_ui.py
	pyuic5 standard_result.ui -o standard_result_ui.py
	pyrcc5 resources.qrc -o resources_rc.py
